// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: activation.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivationService_ActivateUser_FullMethodName = "/activation.ActivationService/ActivateUser"
)

// ActivationServiceClient is the client API for ActivationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivationServiceClient interface {
	ActivateUser(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
}

type activationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivationServiceClient(cc grpc.ClientConnInterface) ActivationServiceClient {
	return &activationServiceClient{cc}
}

func (c *activationServiceClient) ActivateUser(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, ActivationService_ActivateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivationServiceServer is the server API for ActivationService service.
// All implementations must embed UnimplementedActivationServiceServer
// for forward compatibility.
type ActivationServiceServer interface {
	ActivateUser(context.Context, *ActivateRequest) (*ActivateResponse, error)
	mustEmbedUnimplementedActivationServiceServer()
}

// UnimplementedActivationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivationServiceServer struct{}

func (UnimplementedActivationServiceServer) ActivateUser(context.Context, *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateUser not implemented")
}
func (UnimplementedActivationServiceServer) mustEmbedUnimplementedActivationServiceServer() {}
func (UnimplementedActivationServiceServer) testEmbeddedByValue()                           {}

// UnsafeActivationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivationServiceServer will
// result in compilation errors.
type UnsafeActivationServiceServer interface {
	mustEmbedUnimplementedActivationServiceServer()
}

func RegisterActivationServiceServer(s grpc.ServiceRegistrar, srv ActivationServiceServer) {
	// If the following call pancis, it indicates UnimplementedActivationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivationService_ServiceDesc, srv)
}

func _ActivationService_ActivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivationServiceServer).ActivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivationService_ActivateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivationServiceServer).ActivateUser(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivationService_ServiceDesc is the grpc.ServiceDesc for ActivationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activation.ActivationService",
	HandlerType: (*ActivationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateUser",
			Handler:    _ActivationService_ActivateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activation.proto",
}
